#!/bin/zsh
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUILD="$ROOT/.build/release"
OUT="$ROOT/Release"
swift build -c release --package-path "$ROOT"
STAGE="$OUT/stage"
APP="$STAGE/WeBox.app"
rm -rf "$STAGE"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BUILD/WeBox" "$APP/Contents/MacOS/WeBox"
cp "$ROOT/WeBoxApp/Info.plist" "$APP/Contents/Info.plist"
cp "$ROOT/WeBoxApp/Assets/WeBox.icns" "$APP/Contents/Resources/WeBox.icns"
cp "$ROOT/Docs/README.md" "$STAGE/README.md"
hdiutil create -volname "WeBox" -srcfolder "$STAGE" -ov -format UDZO "$OUT/WeBox.dmg"
